### ISSUE TITLE
Slingshot prototyping with PVC and surgical tubing

### ISSUE THREAD

**Issue by mckartha** [FRC830/2024-Tasks#19]
![image](https://github.com/FRC830/2024-Tasks/assets/1145265/34136113-2193-4946-9380-c44d8d9aa3ab)

**Comment by VictorV234** [comment]
Sorry it does not work. It is pretty cool though.

**Comment by VictorV234** [comment]
Because
- The disc wobbles
- it is inaccurate
- does  not shoot far enough
