### ISSUE TITLE
Chassis fabricated - 1/16

### ISSUE THREAD

**Issue by Harsh-Sinha** [FRC830/2024-Tasks#28]
frame is put together and modules are mounted.
NO wiring

**Comment by lethosor** [comment]
4 rails cut today

working on cutting spacers on CNC

then everything can be assembled. hopefully done today

**Comment by mckartha** [comment]
## Chassis assembly

![image](https://github.com/FRC830/2024-Tasks/assets/1145265/50cb5759-fbcb-4aa3-ac42-fb48683119ad)

![image](https://github.com/FRC830/2024-Tasks/assets/1145265/4f269c54-eb5d-4ea4-83b4-2d9f002e8d0f)

**Comment by jiarong6** [comment]
![image](https://github.com/FRC830/2024-Tasks/assets/152462188/6892fcbb-9729-4cb3-aed8-f051a282564c)
done
