### ISSUE TITLE
Retread Swerve Drive

### ISSUE THREAD

**Issue by GrantR02** [FRC830/2024-Tasks#53]
Swerve Drive still needs to be retreaded.

* [ ] remove old tread from wheels
* [ ] cut new rubber tread
* [ ] find the correct fasteners/screws and confirm they work - can be screwed into - all the wheel threads

**Comment by lethosor** [comment]
cleaning wheels today

**Comment by lethosor** [comment]
Dan experimenting. Waiting on another tool to test

**Comment by danpritts** [comment]
have made good progress.  could make these by hand right now if needed but the hole punch I ordered should make it a lot easier.

**Comment by danpritts** [comment]
fasteners are all good and threads in good shape, except for one that I cross-threaded during experimentation today, which will probably need attention.
